version: '3' 

services: 
    backend:  
      image: example-backend
      environment:
        - REQUEST_ORIGIN=http://localhost:666
      ports:
        - 8080:8080
    frontend:  
      image: example-frontend
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080
      ports:
        - 666:5000
