version: '3' 

services: 
    redis:
      image: redis
      ports:
        - 6379:6379
    backend:  
      image: example-backend
      environment:
        - REQUEST_ORIGIN=http://localhost:666
        - REDIS_HOST=redis
      ports:
        - 8080:8080
    frontend:  
      image: example-frontend
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080
      ports:
        - 666:5000